## Day - 16 - Numpy Exploration

A manufacturing company collects daily production data (in units) from
its 3 factories, each producing 5 types of products over a period of 7
days. You are required to analyse this production data using NumPy
array operations.
Tasks to Perform:
1. Array Creation
Create a 3-dimensional NumPy array 'production' of shape (3, 5, 7)
representing production quantities for 3 factories, 5 product types, and
7 days. (Generate random integers between 50 and 200 for this data.)
2. Indexing and Slicing
• Display the production of Factory 1 for all products on Day 3.
• Display the production data of Product 4 across all factories for the
entire week.
3. Array Manipulation
• Reshape the data of Factory 1 into a 2-D array (products × days).
• Combine the data of all factories horizontally to create a single
summary array.
• Split this combined array back into 3 factory arrays.
4. Mathematical and Statistical Operations
• Compute total weekly production of each factory.
• Find the product-wise average production across all factories.
• Identify which factory achieved the highest total output.
• Find the day with the maximum total production across all factories
and products.
• Calculate mean, median, and standard deviation of total production.
5. Logical and Comparison Operations
• Determine which factory had any day’s production below 100 units for
any product.
• Replace all values below 100 with 100.

In [30]:
import numpy as np
shape = (3,5,7)
production = np.random.randint(50, 200, size=(3, 5, 7))
print(production)

[[[169 120 148  98 194  71 198]
  [129 137 123  86  97 161 142]
  [ 66  50  62 177 145 194  68]
  [183 137 119 156 168 172 141]
  [196 142 183 120  66 167 123]]

 [[ 90  71  91 150 150 170 161]
  [145 104 104 165 158 111  54]
  [ 88 158 136 114  97 186 143]
  [187 115 147 122  79  59  73]
  [ 97  88 131 127 146  72 196]]

 [[ 53 100  68 115 170 199 158]
  [ 67 141  74 166 167 156 183]
  [152  65  75 169  86  75  59]
  [ 63 192 176 176 155 130 178]
  [187 160 190  90  65 186 142]]]


In [31]:
print(production[0,:, 2])

print("-"*100)

print(production[:,3,:])

[148 123  62 119 183]
----------------------------------------------------------------------------------------------------
[[183 137 119 156 168 172 141]
 [187 115 147 122  79  59  73]
 [ 63 192 176 176 155 130 178]]


In [32]:
print(production[0])

print("-"*100)

combined = np.hstack((production[0],production[1],production[2]))
print(combined)

print("-"*100)

factory1_split, factory2_split, factory3_split = np.hsplit(combined, 3)
print(factory1_split)
print(factory2_split)
print(factory3_split)

[[169 120 148  98 194  71 198]
 [129 137 123  86  97 161 142]
 [ 66  50  62 177 145 194  68]
 [183 137 119 156 168 172 141]
 [196 142 183 120  66 167 123]]
----------------------------------------------------------------------------------------------------
[[169 120 148  98 194  71 198  90  71  91 150 150 170 161  53 100  68 115
  170 199 158]
 [129 137 123  86  97 161 142 145 104 104 165 158 111  54  67 141  74 166
  167 156 183]
 [ 66  50  62 177 145 194  68  88 158 136 114  97 186 143 152  65  75 169
   86  75  59]
 [183 137 119 156 168 172 141 187 115 147 122  79  59  73  63 192 176 176
  155 130 178]
 [196 142 183 120  66 167 123  97  88 131 127 146  72 196 187 160 190  90
   65 186 142]]
----------------------------------------------------------------------------------------------------
[[169 120 148  98 194  71 198]
 [129 137 123  86  97 161 142]
 [ 66  50  62 177 145 194  68]
 [183 137 119 156 168 172 141]
 [196 142 183 120  66 167 123]]
[[ 90  71  91 150 150 170 161]
 [145 104

In [33]:
total_weekly_production = np.sum(production, axis=(1, 2))
print(total_weekly_production)

print("-"*100)

product_wise_avg = np.mean(production, axis=(0, 2))
print(product_wise_avg)

print("-"*100)

highest_factory_index = np.argmax(total_weekly_production)
highest_factory_total = total_weekly_production[highest_factory_index]
print(f"Factory {highest_factory_index + 1} achieved the highest total output: {highest_factory_total} units")

print("-"*100)

daily_totals = np.sum(production, axis=(0, 1))
max_day_index = np.argmax(daily_totals)
max_day_total = daily_totals[max_day_index]
print(f"Day {max_day_index + 1} had the maximum total production: {max_day_total} units")

print("-"*100)

mean_production = np.mean(production)
median_production = np.median(production)
std_production = np.std(production)
print(f"Mean Production: {mean_production:.2f}")
print(f"Median Production: {median_production:.2f}")
print(f"Standard Deviation: {std_production:.2f}")

[4708 4285 4588]
----------------------------------------------------------------------------------------------------
[130.66666667 127.14285714 112.61904762 139.42857143 136.85714286]
----------------------------------------------------------------------------------------------------
Factory 1 achieved the highest total output: 4708 units
----------------------------------------------------------------------------------------------------
Day 6 had the maximum total production: 2109 units
----------------------------------------------------------------------------------------------------
Mean Production: 129.34
Median Production: 137.00
Standard Deviation: 43.67


In [34]:
below_100_mask = production < 100
factories_below_100 = np.any(below_100_mask, axis=(1, 2))

print("Factories with production < 100 units on any day:")
print(factories_below_100)

Factories with production < 100 units on any day:
[ True  True  True]


In [35]:
production[production < 100] = 100

print(production)

[[[169 120 148 100 194 100 198]
  [129 137 123 100 100 161 142]
  [100 100 100 177 145 194 100]
  [183 137 119 156 168 172 141]
  [196 142 183 120 100 167 123]]

 [[100 100 100 150 150 170 161]
  [145 104 104 165 158 111 100]
  [100 158 136 114 100 186 143]
  [187 115 147 122 100 100 100]
  [100 100 131 127 146 100 196]]

 [[100 100 100 115 170 199 158]
  [100 141 100 166 167 156 183]
  [152 100 100 169 100 100 100]
  [100 192 176 176 155 130 178]
  [187 160 190 100 100 186 142]]]
